var lyrics = [
    
[
{lyric:"Prima Donna", time: 11},
{lyric:"dodged a call from", time: 14},
{lyric:"the Investor", time: 20},
{lyric:"Were you struck dumb?", time: 24},
{lyric:"Were you, Prima Donna?", time: 27},
{lyric:"Now struck dumb", time:39},
{lyric:"the next call she-", time: 44},
{lyric:"uh, picked up", time: 49},
{lyric:"Aha, you’re not so lucky?", time: 54},
{lyric:"Are you, Prima Donna?", time: 57},
{lyric:"The Investor came through", time: 69},
{lyric:"loud and clear", time: 73},
{lyric:"She was dumb, not deaf", time: 79},
{lyric:"Foul speech hit her ear", time: 83},
{lyric:"The poor, Prima Donna", time: 85},
{lyric:"She’s met this man before", time: 98},
{lyric:"and seen how he eats", time: 102},
{lyric:"He made no sense", time: 108},
{lyric:"His voice throbbed endlessly", time: 112},
{lyric:"to our Prima Donna", time: 125},
{lyric:"She phonetically", time: 127},
{lyric:"built a sentence:", time: 133},
{lyric:"“Will this affect my record?”", time: 138},
{lyric:"“It might.” the Investor menaced", time: 143},
{lyric:"The Investor menaced", time: 145},
{lyric:"Tell me, what good", time: 157},
{lyric:"could possibly come?", time: 162},
{lyric:"He gives her the stage", time: 167},
{lyric:"she deserves to perform on", time: 172},
{lyric:"And isn’t it this stinking world", time: 186},
{lyric:"that likes to see beauty suffer?", time: 192},
{lyric:"Well, isn’t it??", time: 197},
{lyric:"Either way, too bad for her", time: 202},
{lyric:"And she went out that night", time: 216},
{lyric:"and blew the lid off the joint", time: 221},
{lyric:"Like an investment", time: 227},
{lyric:"that never disappoints", time: 231},
{lyric:"The Prima Donna", time: 234}
],    
    
[
{lyric:"You're not my dream girl", time: 14},
{lyric:"You're not my reality girl", time: 18},
{lyric:"You're my dreams come true girl", time: 22},
{lyric:"All the troubles in my past. That's just what they are", time: 32},
{lyric:"And all the delusions that took host then past. They've only made my immunity strong", time: 49},
{lyric:"You're not my dream girl", time: 64},
{lyric:"You're not my reality girl", time: 68},
{lyric:"You're my dreams come true girl", time: 73},
{lyric:"I didn't blast your eyes up to moons", time: 83},
{lyric:"I hope this for you to not be ending very soon", time: 92},
{lyric:"Just crying in orbit with these mirrors of perfection", time: 109},
{lyric:"To die in the arms of your affection", time: 116},
{lyric:"What land is this?", time: 135},
{lyric:"May I never wake", time: 138},
{lyric:"What land is this?", time: 142},
{lyric:"May I never wake", time: 147},
{lyric:"You're not my dream girl", time: 198}, 
{lyric:"You're not my reality girl", time: 202}, 
{lyric:"You're my dreams come true girl", time: 207},
{lyric:"You're not my dream girl", time: 214},
{lyric:"All the troubles in my past. That's just what they are", time: 216},
{lyric:"And all the delusions that took host then past, have only made my immunity strong", time: 234},
{lyric:"I'm not your dream girl", time: 247},
{lyric:"No no no no no no no your dream", time: 252},
{lyric:"Take me dancing tonight", time: 291},
{lyric:"Take me out, it's Saturday!", time: 313}    
],     
    
[
{lyric:"I love my job almost as much as I do you", time: 1},
{lyric:"It's a good job", time: 9},
{lyric:"I may not get paid as much", time: 19},
{lyric:"but I more than make up", time: 23},
{lyric:"with an enormous sense of self-worth", time: 28},
{lyric:"My job", time: 38},
{lyric:"My job", time: 46},
{lyric:"My job", time: 52},
{lyric:"My job", time: 59},    
{lyric:"Some people just work to", time: 68},
{lyric:"pay the bills and put bread on the table", time: 71},
{lyric:"I couldn't do that", time: 87},
{lyric:"I need feeling and purpose", time: 91},
{lyric:"My job", time: 106},
{lyric:"My job", time: 114}, 
{lyric:"My job", time: 120},
{lyric:"My job", time: 128},    
{lyric:"Although i admit sometimes", time: 134},
{lyric:"it's not very fun", time: 138},
{lyric:"in fact, it can be pretty stressful", time: 141},
{lyric:"at the end of the day", time: 145},
{lyric:"I know I begun and completed the work", time: 148},
{lyric:"only by my own willpower", time: 151},
{lyric:"There is work that is play", time: 162},
{lyric:"There is play that is work", time: 172},
{lyric:"And play that is play", time: 176},
{lyric:"And work that is work", time: 183},
{lyric:"And in only one of these", time: 187},
{lyric:"lies happiness", time: 191},
{lyric:"I'm a pretty lucky guy", time: 196},
{lyric:"I love you and i love my job", time: 199},
{lyric:"My job", time: 210}, 
{lyric:"My job", time: 218}, 
{lyric:"My job", time: 224}     
],    
    
   
[
{lyric:"In this spare room", time: 0},
{lyric:"We better see what we have and whom", time: 7},
{lyric:"An I.O.U. for the Same Thing", time: 13},
{lyric:"Only angels have wings", time: 21},
{lyric:"So they say", time: 25},
{lyric:"Here I stand, alive unto you", time: 29},
{lyric:"My fate's mercy seat", time: 37},
{lyric:"Sought blood to gulp and flesh to eat", time: 45},
{lyric:"And I can't blame you enough", time:52},
{lyric:"But I'm indebted to your mercy and your love", time: 59},
{lyric:"Here I stand, alive unto you, alive unto you", time: 67},
{lyric:"Because you saved my life", time: 78},
{lyric:"Now I see there's so much to lose so much to lose", time: 81},
{lyric:"Because you saved my life", time: 90},
{lyric:"My life, you saved my life", time: 94},
{lyric:"Darling, now I must live for you", time: 107},
{lyric:"One reprieve grants another until each world is born anew", time: 113},
{lyric:"Here I stand, alive unto you, alive unto you", time: 137},
{lyric:"Because you saved my life", time: 148},
{lyric:"Now I see there's so much to lose, so much to lose", time: 151},
{lyric:"Because you saved my life", time: 162},
{lyric:"Here I stand, alive unto you, alive unto you", time: 164},
{lyric:"Because you saved my life", time: 172},
{lyric:"Now I see there's so much to lose, so much to lose", time: 176},
{lyric:"Because you saved my life", time: 185},
{lyric:"Never understand, never can ignore", time: 235},
{lyric:"I'm rotten to the core, since 1994", time: 237},
{lyric:"Never understand, never can ignore", time: 246},
{lyric:"I'm rotten to the core, since 1994", time: 248}
]      
    
    
]